name: Run Tests

on:
  pull_request: {}
  push: {}

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE_2019 }} # Can be generated at https://license.unity3d.com/manual

jobs:
  build:
    name: Run Unity Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Load Library
        uses: actions/cache@v1.1.0
        with:
          path: ragdoll-olympics/Library
          key: Library
      - name: Run Tests
        uses: webbertakken/unity-test-runner@v1.4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: "ragdoll-olympics"
          unityVersion: 2019.4.10f1
      - uses: actions/upload-artifact@v1
        with:
          name: Test results
          path: artifacts